import { expect, it, vi } from "vitest";
import { browserbaseProvider } from "./browserbase-provider";
const input = { requestId: "job-1", approvedHost: "example.com", targetUrl: "https://example.com" };
function fixture(enabled = true) {
  const store = { reserve: vi.fn().mockResolvedValue(undefined), attach: vi.fn().mockResolvedValue(undefined), uncertain: vi.fn().mockResolvedValue(undefined) };
  const fetcher = vi.fn().mockResolvedValue(new Response(JSON.stringify({ id: "session-1", connectUrl: "secret", signingKey: "secret" })));
  return { store, fetcher, provider: browserbaseProvider({ enabled, apiKey: "test-key", projectId: "project-1", store, fetcher }) };
}
it("is disabled before any reservation or request", async () => { const f = fixture(false); await expect(f.provider.create(input)).rejects.toThrow(); expect(f.fetcher).not.toHaveBeenCalled(); expect(f.store.reserve).not.toHaveBeenCalled(); });
it("fails closed when durable reservation fails", async () => { const f = fixture(); f.store.reserve.mockRejectedValue(new Error("budget")); await expect(f.provider.create(input)).rejects.toThrow(); expect(f.fetcher).not.toHaveBeenCalled(); });
it("sends restrictive settings and exposes no connection credentials", async () => { const f = fixture(); expect(await f.provider.create(input)).toEqual({ sessionId: "session-1" }); expect(JSON.parse(f.fetcher.mock.calls[0][1].body)).toMatchObject({ projectId: "project-1", timeout: 300, proxies: false, keepAlive: false, browserSettings: { allowedDomains: ["example.com"] } }); expect(f.fetcher.mock.calls[0][1].redirect).toBe("error"); expect(f.store.attach).toHaveBeenCalledWith("job-1", "session-1"); });
it("does not reserve or call Browserbase without a project id", async () => { const f = fixture(); const provider = browserbaseProvider({ enabled: true, apiKey: "test-key", projectId: "", store: f.store, fetcher: f.fetcher }); await expect(provider.create(input)).rejects.toThrow("inte aktiverad"); expect(f.store.reserve).not.toHaveBeenCalled(); expect(f.fetcher).not.toHaveBeenCalled(); });
it("retains reservation after timeout without retry", async () => { const f = fixture(); f.fetcher.mockRejectedValue(new Error("secret token")); await expect(f.provider.create(input)).rejects.toThrow("status är osäker"); expect(f.fetcher).toHaveBeenCalledTimes(1); expect(f.store.uncertain).toHaveBeenCalledWith("job-1"); });
it("quarantines persistence failure after creation", async () => { const f = fixture(); f.store.attach.mockRejectedValue(new Error("db")); await expect(f.provider.create(input)).rejects.toThrow(); expect(f.store.uncertain).toHaveBeenCalled(); });
it("can stop while disabled without refunding reservations", async () => { const f = fixture(false); expect(await f.provider.stop("session-1")).toEqual({ stopRequested: true }); expect(JSON.parse(f.fetcher.mock.calls[0][1].body)).toEqual({ status: "REQUEST_RELEASE" }); expect(f.store.reserve).not.toHaveBeenCalled(); });
it("rejects path injection", async () => { const f = fixture(); await expect(f.provider.stop("../sessions")).rejects.toThrow(); expect(f.fetcher).not.toHaveBeenCalled(); });
it.each(["COMPLETED", "TIMED_OUT", "ERROR"])("verifies terminal receipt %s", async status => { const f = fixture(false); f.fetcher.mockResolvedValue(new Response(JSON.stringify({ id: "session-1", status, endedAt: "2026-01-01T00:00:00Z", signingKey: "secret" }))); expect(await f.provider.inspect("session-1")).toEqual({ sessionId: "session-1", status, terminated: true }); expect(f.fetcher.mock.calls[0][1].method).toBe("GET"); });
it.each([null, "invalid", "2999-01-01T00:00:00Z"])("does not trust missing or future end time %s", async endedAt => { const f = fixture(); f.fetcher.mockResolvedValue(new Response(JSON.stringify({ id: "session-1", status: "COMPLETED", endedAt }))); expect((await f.provider.inspect("session-1")).terminated).toBe(false); });
it("rejects another session receipt", async () => { const f = fixture(); f.fetcher.mockResolvedValue(new Response(JSON.stringify({ id: "other", status: "COMPLETED" }))); await expect(f.provider.inspect("session-1")).rejects.toThrow(); });
