import * as LocalAuthentication from "expo-local-authentication";
import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { assistant, dismiss, type Snapshot } from "../lib/api";
import { supabase } from "../lib/auth";

export default function Home() {
  const [token, setToken] = useState<string | null>(null), [data, setData] = useState<Snapshot | null>(null), [mode, setMode] = useState<"handle" | "note">("handle"), [email, setEmail] = useState(""), [password, setPassword] = useState(""), [error, setError] = useState("");
  const load = async (accessToken: string) => { try { setError(""); setData(await assistant(accessToken)); } catch (e) { setError(e instanceof Error ? e.message : "Kunde inte ladda Notiscenter."); } };
  useEffect(() => { supabase.auth.getSession().then(({ data }) => { if (data.session) LocalAuthentication.authenticateAsync({ promptMessage: "Öppna Solvani" }).then(r => { if (r.success) { setToken(data.session!.access_token); void load(data.session!.access_token); } }); }); }, []);
  const login = async () => { const { data, error: authError } = await supabase.auth.signInWithPassword({ email, password }); if (authError || !data.session) return setError(authError?.message || "Kunde inte logga in."); const face = await LocalAuthentication.authenticateAsync({ promptMessage: "Skydda appen med Face ID" }); if (!face.success) return; setToken(data.session.access_token); void load(data.session.access_token); };
  if (!token) return <SafeAreaView style={s.login}><Text style={s.title}>Solvani</Text><Text style={s.muted}>Logga in med samma privata konto som på webben.</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="E-post" placeholderTextColor="#8f98a4" style={s.input}/><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Lösenord" placeholderTextColor="#8f98a4" style={s.input}/><Pressable onPress={() => void login()} style={s.primary}><Text style={s.button}>Logga in säkert</Text></Pressable>{error ? <Text style={s.error}>{error}</Text> : null}</SafeAreaView>;
  const candidates = data?.candidates || [];
  const remove = async (id: string, kind: string) => { await dismiss(token, id, kind); setData(current => current ? { ...current, candidates: current.candidates.filter(c => !(c.messageId === id && c.kind === kind)) } : current); };
  return <SafeAreaView style={s.page}><View style={s.header}><Text style={s.title}>Notiscenter</Text><Text style={s.muted}>Beslut, inte brus.</Text></View><View style={s.tabs}><Pressable onPress={() => setMode("handle")} style={[s.tab, mode === "handle" && s.active]}><Text>Bör hanteras ({candidates.length})</Text></Pressable><Pressable onPress={() => setMode("note")} style={[s.tab, mode === "note" && s.active]}><Text>Bör noteras ({data?.notes?.length || 0})</Text></Pressable></View><ScrollView contentContainerStyle={s.list}>{!data && !error && <ActivityIndicator />}{error ? <Text style={s.error}>{error}</Text> : mode === "handle" ? candidates.map(c => <View key={`${c.messageId}:${c.kind}`} style={s.card}><Text style={s.source}>{c.plan.evidence.source} · {c.plan.evidence.account}</Text><Text style={s.person}>{c.plan.evidence.personName}</Text><Text style={s.subject}>{c.plan.evidence.title}</Text><Text style={s.muted}>{c.plan.reason}</Text><View style={s.actions}><Pressable style={s.primary}><Text style={s.button}>Granska</Text></Pressable><Pressable onPress={() => void remove(c.messageId, c.kind)} style={s.secondary}><Text style={s.white}>Inte relevant</Text></Pressable></View></View>) : (data?.notes || []).map(n => <View key={n.messageId} style={s.card}><Text style={s.source}>{n.source} · prioritet {n.priority}/10</Text><Text style={s.person}>{n.personName}</Text><Text style={s.subject}>{n.title}</Text><Text style={s.muted}>{n.summary}</Text></View>)}</ScrollView></SafeAreaView>;
}
const s = StyleSheet.create({ page:{flex:1,backgroundColor:"#0b0d10"},login:{flex:1,justifyContent:"center",padding:24,backgroundColor:"#0b0d10",gap:12},header:{padding:22,paddingBottom:8},title:{color:"#fff",fontSize:28,fontWeight:"700"},muted:{color:"#a9b0bb",marginTop:6,lineHeight:20},input:{backgroundColor:"#171b20",borderRadius:12,color:"#fff",padding:14},tabs:{flexDirection:"row",gap:8,padding:16},tab:{backgroundColor:"#1a1e24",padding:12,borderRadius:12},active:{backgroundColor:"#d8ff75"},list:{padding:16,gap:12},card:{backgroundColor:"#15191e",padding:16,borderRadius:16,gap:6},source:{color:"#d8ff75",fontSize:12},person:{color:"#fff",fontWeight:"700",fontSize:16},subject:{color:"#fff",fontSize:15},actions:{flexDirection:"row",gap:10,marginTop:8},primary:{backgroundColor:"#d8ff75",padding:12,borderRadius:10,alignItems:"center"},secondary:{backgroundColor:"#282e36",padding:12,borderRadius:10},button:{color:"#111",fontWeight:"700"},white:{color:"#fff"},error:{color:"#ff8888",paddingTop:8} });
