"use client";
import {useState} from "react";
import type {PlaceCandidate} from "@/lib/calendar/places-routing";
export type MeetingPerson={id:string;display_name:string;organization:string|null;emails:string[];invitationEmail:string};
export function MeetingPeoplePicker({value,onChange}:{value:MeetingPerson[];onChange:(people:MeetingPerson[])=>void}){
 const [query,setQuery]=useState(""),[results,setResults]=useState<MeetingPerson[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function search(){setBusy(true);setError("");try{const r=await fetch(`/api/calendar/context?includeEmails=true&search=${encodeURIComponent(query)}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setResults(d.people);if(!d.people.length)setError("Inga kontakter hittades. Prova personens namn.");}catch(e){setError(e instanceof Error?e.message:"Sökningen misslyckades.");}finally{setBusy(false);}}
 return <fieldset><legend>Personer från Contacts</legend><label>Sök kontakt efter namn<input value={query} maxLength={100} onChange={e=>setQuery(e.target.value)}/></label><button type="button" className="btn" disabled={busy||query.trim().length<2} onClick={search}>{busy?"Söker…":"Sök kontakt"}</button>
 {error&&<p role="status">{error}</p>}
 {results.filter(p=>!value.some(v=>v.id===p.id)).map(p=><p key={p.id}><button type="button" className="btn" disabled={value.length>=30} onClick={()=>onChange([...value,{...p,emails:p.emails??[],invitationEmail:""}])}>Lägg till {p.display_name}{p.organization?` · ${p.organization}`:""}</button></p>)}
 {value.map(p=><article className="calendar-hold" key={p.id}><strong>{p.display_name}</strong><p>{p.organization}</p>{p.emails.length?<label>Adress för inbjudan<select value={p.invitationEmail} onChange={e=>onChange(value.map(v=>v.id===p.id?{...v,invitationEmail:e.target.value}:v))}><option value="">Koppla kontakt utan inbjudan</option>{p.emails.map(email=><option key={email}>{email}</option>)}</select></label>:<p>Ingen e-postadress sparad. Kontakten kopplas till mötet. Lägg till en adress nedan om du vill bjuda in personen.</p>}<button type="button" className="btn" onClick={()=>onChange(value.filter(v=>v.id!==p.id))}>Ta bort {p.display_name}</button></article>)}
 <p>Kontaktkopplingen sparas på mötet. Inbjudningar skickas bara till de adresser du väljer och sedan godkänner.</p></fieldset>;
}
export function MeetingPlacePicker({value,onChange,enabled}:{value:PlaceCandidate|null;onChange:(place:PlaceCandidate|null)=>void;enabled:boolean}){
 const [query,setQuery]=useState(""),[results,setResults]=useState<PlaceCandidate[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function search(){setBusy(true);setError("");try{const r=await fetch("/api/calendar/planning",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"places",query})});const d=await r.json();if(!r.ok)throw new Error(d.error);setResults(d.places);if(!d.places.length)setError("Inga platser hittades.");}catch(e){setError(e instanceof Error?e.message:"Platssökningen misslyckades.");}finally{setBusy(false);}}
 return <fieldset><legend>Mötesplats · Google Maps</legend>{!enabled&&<p>Maps-sökningen är inte tillgänglig just nu.</p>}<label>Sök plats eller adress<input value={query} maxLength={300} onChange={e=>setQuery(e.target.value)}/></label><button type="button" className="btn" disabled={!enabled||busy||query.trim().length<3} onClick={search}>{busy?"Söker…":"Sök i Google Maps"}</button>{error&&<p role="alert">{error}</p>}{results.map(p=><article className="calendar-hold" key={p.id}><strong>{p.name}</strong><p>{p.address}</p><button type="button" className="btn" onClick={()=>{onChange(p);setResults([]);}}>Välj plats</button></article>)}{value&&<p>Vald plats: {value.name} · {value.address} <a href={value.mapsUrl} target="_blank" rel="noopener noreferrer">Visa på Google Maps</a> <button type="button" className="btn" onClick={()=>onChange(null)}>Ta bort plats</button></p>}<p translate="no">Google Maps</p></fieldset>;
}
