"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
type Item={id:string;title:string;start:string|null;end:string|null;timezone:string;source:string;locationKind:string;placeLabel:string;status:string};
export function ContactCalendar({personId}:{personId:string}) {
 const [items,setItems]=useState<Item[]|null>(null),[error,setError]=useState("");
 useEffect(()=>{const c=new AbortController();void fetch(`/api/calendar/context?personId=${encodeURIComponent(personId)}`,{cache:"no-store",signal:c.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);setItems(data.items);}).catch(e=>{if(e.name!=="AbortError")setError(e.message);});return()=>c.abort();},[personId]);
 return <section className="contact-calendar card" aria-label="Kalender med kontakten"><div className="contact-calendar-heading"><div><span className="intel-label">Kalender</span><h2>Planer med kontakten</h2></div><Link className="btn" href="/?view=calendar">Öppna kalendern</Link></div>{error?<p className="negative" role="alert">Kalenderkopplingarna kunde inte hämtas just nu.</p>:items===null?<p className="muted">Kontrollerar kopplade planer…</p>:items.length===0?<div className="contact-calendar-empty"><strong>Inga planer är kopplade ännu</strong><p>Kommande möten och bokningar med den här kontakten visas här när de har kopplats till kalendern.</p></div>:<div className="contact-calendar-list">{items.map(item=><article className="contact-calendar-item" key={item.id}><strong>{item.title}</strong><span>{item.start?new Date(item.start).toLocaleString("sv-SE",{timeZone:item.timezone,dateStyle:"medium",timeStyle:"short"}):"Utanför det synkade kalenderintervallet"}{item.status==="cancelled"?" · Avbokad":""}</span><small>{item.locationKind==="digital"?"Digitalt möte":item.placeLabel||"Plats ej angiven"}</small></article>)}</div>}<p className="muted contact-calendar-note">En kontaktkoppling är inte en kalenderinbjudan.</p></section>;
}
