"use client";
import {useEffect,useState} from "react";
import {CheckCircle2,ChevronDown,FileText,Image as ImageIcon,Music2,Play,Upload,ExternalLink,UserRound,XCircle} from "lucide-react";

type ImportOrigin="google_drive"|"onedrive"|"google_photos"|"device";
type Asset={id:string;asset_kind:string;title:string;filename:string;mime_type:string;size_bytes:number;sensitivity:string;document_type?:string|null;summary:string;retention_reason:string;importance_score:number;reusable:boolean;source_type:string;external_origin?:ImportOrigin|null;created_at:string;previewUrl?:string;transcript?:string|null;sourcePerson?:{id:string;name:string;organization:string|null}|null};
type CloudConnection={id:string;provider:"google-drive"|"microsoft-onedrive"|"google-photos";label:string;account:string;status:string;health:string;updatedAt:string};

const originLabel:Record<ImportOrigin,string>={google_drive:"Google Drive",onedrive:"OneDrive",google_photos:"Google Foto",device:"Din enhet"};
const sourceLabel:Record<string,string>={email:"E-post",whatsapp:"WhatsApp",instagram:"Instagram",manual:"Manuellt",google_photos:"Google Foto"};
const readableDate=(value:string)=>new Intl.DateTimeFormat("sv-SE",{day:"numeric",month:"short",year:"numeric"}).format(new Date(value));

function Sender({asset}:{asset:Asset}){
 const person=asset.sourcePerson;
 return person?<a className="vault-sender" href={`/contacts/${person.id}`} aria-label={`Öppna kontaktkort för ${person.name}`}><span className="vault-person-avatar">{person.name.slice(0,1).toUpperCase()}</span><span><small>Skickat av</small><strong>{person.name}</strong>{person.organization&&<em>{person.organization}</em>}</span></a>:<div className="vault-sender unknown"><span className="vault-person-avatar"><UserRound size={15}/></span><span><small>Avsändare</small><strong>Okänd kontakt</strong><em>Kan kopplas när kontakten identifieras</em></span></div>;
}

function Transcript({value}:{value:string}){
 const [expanded,setExpanded]=useState(false);
 const isLong=value.length>700;
 return <div className={`vault-transcript ${expanded?"expanded":""}`}><p>{value}</p>{isLong&&<button className="btn text" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{expanded?"Visa mindre":"Visa hela transkriberingen"}<ChevronDown size={14}/></button>}</div>;
}

function AssetCard({asset,onOpen}:{asset:Asset;onOpen:(id:string)=>void}){
 const image=asset.mime_type.startsWith("image/"); const audio=asset.mime_type.startsWith("audio/"); const video=asset.mime_type.startsWith("video/");
 const kind=image?"Bild":audio?"Ljudmeddelande":video?"Video":asset.document_type||"Dokument";
 return <article className={`vault-asset-card ${image?"is-image":""}`}>
  {image&&asset.previewUrl?<img className="vault-image" src={asset.previewUrl} alt={asset.summary||asset.title||"Bild från kontakt"}/>:video&&asset.previewUrl?<video className="vault-video" controls preload="metadata" src={asset.previewUrl}>Din webbläsare kan inte spela upp videon.</video>:<div className="vault-kind-icon">{audio?<Music2 size={19}/>:video?<Play size={19}/>:asset.asset_kind==="document"?<FileText size={19}/>:<ImageIcon size={19}/>}</div>}
  <div className="vault-asset-content"><div className="vault-card-top"><div><span className="vault-kind">{kind}</span><h3>{asset.title||asset.filename||kind}</h3></div><span className="vault-date">{readableDate(asset.created_at)}</span></div><Sender asset={asset}/>
   {audio&&asset.previewUrl&&<audio controls preload="metadata" src={asset.previewUrl}>Din webbläsare kan inte spela upp ljudet.</audio>}
   {(audio||video)&&asset.transcript?<><span className="vault-section-label">Transkribering</span><Transcript value={asset.transcript}/></>:asset.summary&&<p className="vault-summary">{asset.summary}</p>}
   <div className="vault-card-footer"><span>{sourceLabel[asset.source_type]??asset.source_type}</span><span className="pill">{asset.sensitivity}</span><button className="btn" onClick={()=>void onOpen(asset.id)}><ExternalLink size={13}/>Öppna original</button></div>
  </div>
 </article>;
}

export function DocumentVault(){
 const [assets,setAssets]=useState<Asset[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [origin,setOrigin]=useState<ImportOrigin>("device"); const [cloudConnections,setCloudConnections]=useState<CloudConnection[]>([]);
 const [connectionResult,setConnectionResult]=useState<"connected"|"denied"|"invalid"|"failed"|"configuration"|null>(null); const [connectionProvider,setConnectionProvider]=useState<"google-drive"|"onedrive"|"google-photos">("google-drive");
 const [photoPicker,setPhotoPicker]=useState<{sessionId:string;pickerUri:string}|null>(null);
 const load=async()=>{const r=await fetch("/api/vault/assets",{cache:"no-store"});const d=await r.json() as {assets?:Asset[];error?:string};if(!r.ok)throw new Error(d.error??"Dokumentvalvet kunde inte läsas.");setAssets(d.assets??[]);};
 useEffect(()=>{queueMicrotask(()=>void load().catch(e=>setMessage(e instanceof Error?e.message:"Dokumentvalvet kunde inte läsas.")));},[]);
 useEffect(()=>{queueMicrotask(()=>void fetch("/api/documents/connections",{cache:"no-store"}).then(async response=>{const body=await response.json() as {connections?:CloudConnection[]};if(response.ok)setCloudConnections(body.connections??[]);}).catch(()=>undefined));},[]);
 useEffect(()=>{queueMicrotask(()=>{const params=new URLSearchParams(window.location.search);const result=params.get("documents");const provider=params.get("documentProvider");if(provider==="onedrive"||provider==="google-photos")setConnectionProvider(provider);if(result==="connected"||result==="denied"||result==="invalid"||result==="failed"||result==="configuration")setConnectionResult(result);});},[]);
 const dismissConnectionResult=()=>{setConnectionResult(null);const url=new URL(window.location.href);url.searchParams.delete("documents");url.searchParams.delete("documentProvider");window.history.replaceState({},"",`${url.pathname}${url.search}${url.hash}`);};
 const upload=async(file?:File)=>{if(!file)return;setBusy(true);setMessage("");try{const form=new FormData();form.set("file",file);form.set("sourceType","manual");form.set("externalOrigin",origin);form.set("forceSave","true");const r=await fetch("/api/vault/assets",{method:"POST",body:form});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error??"Filen kunde inte sparas.");setMessage(`Filen från ${originLabel[origin]} är sparad i det säkra dokumentvalvet.`);await load();}catch(e){setMessage(e instanceof Error?e.message:"Filen kunde inte sparas.");}finally{setBusy(false);}};
 const open=async(id:string)=>{const r=await fetch(`/api/vault/assets?assetId=${encodeURIComponent(id)}`,{cache:"no-store"});const d=await r.json() as {url?:string;error?:string};if(!r.ok||!d.url){setMessage(d.error??"Dokumentet kunde inte öppnas.");return;}window.open(d.url,"_blank","noopener,noreferrer");};
 const chooseGooglePhotos=async()=>{const pickerWindow=window.open("","solvani-google-photos-picker");setBusy(true);setMessage("");try{const response=await fetch("/api/documents/google-photos/picker",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"start"})});const data=await response.json() as {sessionId?:string;pickerUri?:string;error?:string};if(!response.ok||!data.sessionId||!data.pickerUri)throw new Error(data.error??"Google Foto kunde inte öppnas.");const pickerUri=`${data.pickerUri}/autoclose`;setPhotoPicker({sessionId:data.sessionId,pickerUri:data.pickerUri});if(pickerWindow){pickerWindow.opener=null;pickerWindow.location.replace(pickerUri);}setMessage(pickerWindow?"Bildväljaren är öppen i en ny flik. Välj upp till tio bilder och återvänd sedan hit för att hämta dem.":"Google Foto är redo. Öppna bildväljaren nedan, välj upp till tio bilder och hämta dem sedan hit.");}catch(error){pickerWindow?.close();setMessage(error instanceof Error?error.message:"Google Foto kunde inte öppnas.");}finally{setBusy(false);}};
 const importGooglePhotos=async()=>{if(!photoPicker)return;setBusy(true);try{const response=await fetch("/api/documents/google-photos/picker",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"import",sessionId:photoPicker.sessionId})});const data=await response.json() as {status?:string;imported?:number;skipped?:number;error?:string};if(!response.ok)throw new Error(data.error??"Bilderna kunde inte hämtas.");if(data.status==="waiting"){setMessage("Google Foto väntar fortfarande på ditt bildval. Öppna bildväljaren, välj bilder och försök sedan igen.");return;}setPhotoPicker(null);setMessage(`${data.imported??0} valda bilder är nu sparade i det säkra valvet.${data.skipped?` ${data.skipped} filer hoppades över.`:""}`);await load();}catch(error){setMessage(error instanceof Error?error.message:"Bilderna kunde inte hämtas.");}finally{setBusy(false);}};
 const cloudActions=<div className="document-connection-card"><div><span className="eyebrow">Cloud documents & photos</span><strong>Anslut bara material du väljer</strong><p>Solvani får läsrättighet först när du ansluter en tjänst. Google Foto använder alltid Googles bildväljare – hela biblioteket skannas aldrig.</p></div><div className="document-connection-actions">{(["google-drive","microsoft-onedrive","google-photos"] as const).map(provider=>{const connection=cloudConnections.find(item=>item.provider===provider&&item.status==="connected");const label=provider==="google-drive"?"Google Drive":provider==="microsoft-onedrive"?"OneDrive":"Google Foto";if(!connection)return <a className="btn" key={provider} href={provider==="google-drive"?"/api/documents/connect/google/start":provider==="microsoft-onedrive"?"/api/documents/connect/microsoft/start":"/api/documents/connect/google-photos/start"}>Anslut {label}</a>;return <span className="document-connected-actions" key={provider}><span className="pill"><CheckCircle2 size={12}/>{label} · {connection.account}</span>{provider==="google-photos"&&<button className="btn" disabled={busy} onClick={()=>void chooseGooglePhotos()}>Välj bilder</button>}</span>;})}</div></div>;
 const providerLabel=connectionProvider==="onedrive"?"OneDrive":connectionProvider==="google-photos"?"Google Foto":"Google Drive";
 const resultCopy={connected:{title:`${providerLabel} är anslutet`,body:`Anslutningen är klar. Solvani kan nu använda de filer du aktivt väljer från ${providerLabel}.`},denied:{title:"Anslutningen avbröts",body:`Ingen åtkomst till ${providerLabel} gavs och inga filer har anslutits.`},invalid:{title:"Anslutningen kunde inte verifieras",body:`Säkerhetskontrollen för ${providerLabel} gick ut. Försök ansluta igen.`},failed:{title:"Anslutningen misslyckades",body:`${providerLabel} kunde inte kopplas just nu. Försök igen, eller kontrollera behörigheten.`},configuration:{title:`${providerLabel} behöver konfigureras`,body:"Anslutningen saknar en serverinställning. Ingen åtkomst har getts."}} as const;
 return <section className="document-vault">{connectionResult&&<div className="connection-result-overlay" role="dialog" aria-modal="true" aria-labelledby="document-connection-result"><div className={`connection-result-card ${connectionResult==="connected"?"success":"error"}`}>{connectionResult==="connected"?<CheckCircle2 size={22}/>:<XCircle size={22}/>}<div><span className="eyebrow">Documents & Media</span><h2 id="document-connection-result">{resultCopy[connectionResult].title}</h2><p>{resultCopy[connectionResult].body}</p></div><button className="btn primary" onClick={dismissConnectionResult}>Fortsätt</button></div></div>}{cloudActions}{photoPicker&&<div className="assistant-notice"><strong>Google Foto är redo.</strong> <a className="text-link" target="_blank" rel="noreferrer" href={`${photoPicker.pickerUri}/autoclose`}>Öppna bildväljaren</a> och välj de bilder du vill använda. <button className="btn" disabled={busy} onClick={()=>void importGooglePhotos()}>Hämta valda bilder</button></div>}<div className="personal-context-head"><div><span className="eyebrow">Secure Document & Media Vault</span><h2>Viktiga dokument & media</h2><p>Bilder, ljud och dokument från dina konversationer – kopplade till rätt kontakt och redo att användas som underlag när Solvani föreslår ett svar.</p></div><label className="btn primary"><Upload size={14}/>Importera vald fil<input hidden type="file" disabled={busy} onChange={e=>void upload(e.target.files?.[0])}/></label></div><div className="toolbar" aria-label="Filursprung"><label className="muted" htmlFor="vault-import-origin">Filursprung</label><select id="vault-import-origin" className="filter" value={origin} onChange={event=>setOrigin(event.target.value as ImportOrigin)} disabled={busy}><option value="device">Din enhet</option><option value="google_drive">Google Drive</option><option value="onedrive">OneDrive</option><option value="google_photos">Google Foto</option></select><small className="muted">För manuellt valda filer. Konversationsmedia sparas automatiskt med sin avsändare.</small></div>{message&&<p className="assistant-notice">{message}</p>}{assets.length===0?<div className="empty-card">Inga sparade dokument ännu. Bilagor från anslutna konton och filer du väljer kan läggas i valvet.</div>:<div className="document-vault-grid">{assets.map(asset=><AssetCard asset={asset} key={asset.id} onOpen={open}/>)}</div>}</section>;
}
