"use client";
import {useEffect,useState} from "react";
import {CheckCircle2,FileText,Image as ImageIcon,Upload,ExternalLink,XCircle} from "lucide-react";

type ImportOrigin="google_drive"|"onedrive"|"device";
type Asset={id:string;asset_kind:string;title:string;filename:string;mime_type:string;size_bytes:number;sensitivity:string;document_type?:string|null;summary:string;retention_reason:string;importance_score:number;reusable:boolean;source_type:string;external_origin?:ImportOrigin|null;created_at:string};
type CloudConnection={id:string;provider:"google-drive"|"microsoft-onedrive";label:string;account:string;status:string;health:string;updatedAt:string};

const originLabel:Record<ImportOrigin,string>={google_drive:"Google Drive",onedrive:"OneDrive",device:"Din enhet"};

export function DocumentVault(){
 const [assets,setAssets]=useState<Asset[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [origin,setOrigin]=useState<ImportOrigin>("device");
 const [cloudConnections,setCloudConnections]=useState<CloudConnection[]>([]);
 const [connectionResult,setConnectionResult]=useState<"connected"|"denied"|"invalid"|"failed"|"configuration"|null>(null);
 const [connectionProvider,setConnectionProvider]=useState<"google-drive"|"onedrive">("google-drive");
 const load=async()=>{const r=await fetch("/api/vault/assets",{cache:"no-store"});const d=await r.json() as {assets?:Asset[];error?:string};if(!r.ok)throw new Error(d.error??"Dokumentvalvet kunde inte läsas.");setAssets(d.assets??[]);};
 useEffect(()=>{queueMicrotask(()=>void load().catch(e=>setMessage(e instanceof Error?e.message:"Dokumentvalvet kunde inte läsas.")));},[]);
 useEffect(()=>{queueMicrotask(()=>void fetch("/api/documents/connections",{cache:"no-store"}).then(async response=>{const body=await response.json() as {connections?:CloudConnection[]};if(response.ok)setCloudConnections(body.connections??[]);}).catch(()=>undefined));},[]);
 useEffect(()=>{const params=new URLSearchParams(window.location.search);const result=params.get("documents");const provider=params.get("documentProvider");if(provider==="onedrive")setConnectionProvider("onedrive");if(result==="connected"||result==="denied"||result==="invalid"||result==="failed"||result==="configuration")setConnectionResult(result);},[]);
 const dismissConnectionResult=()=>{setConnectionResult(null);const url=new URL(window.location.href);url.searchParams.delete("documents");url.searchParams.delete("documentProvider");window.history.replaceState({},"",`${url.pathname}${url.search}${url.hash}`);};
 const upload=async(file?:File)=>{if(!file)return;setBusy(true);setMessage("");try{const form=new FormData();form.set("file",file);form.set("sourceType","manual");form.set("externalOrigin",origin);form.set("forceSave","true");const r=await fetch("/api/vault/assets",{method:"POST",body:form});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error??"Filen kunde inte sparas.");setMessage(`Filen från ${originLabel[origin]} är sparad i det säkra dokumentvalvet.`);await load();}catch(e){setMessage(e instanceof Error?e.message:"Filen kunde inte sparas.");}finally{setBusy(false);}};
 const open=async(id:string)=>{const r=await fetch(`/api/vault/assets?assetId=${encodeURIComponent(id)}`,{cache:"no-store"});const d=await r.json() as {url?:string;error?:string};if(!r.ok||!d.url){setMessage(d.error??"Dokumentet kunde inte öppnas.");return;}window.open(d.url,"_blank","noopener,noreferrer");};
 const cloudActions=<div className="document-connection-card"><div><span className="eyebrow">Cloud documents</span><strong>Anslut filer du väljer</strong><p>Solvani får endast läsrättighet till filer du väljer. Original i Drive och OneDrive ändras eller delas aldrig härifrån.</p></div><div className="document-connection-actions">{(["google-drive","microsoft-onedrive"] as const).map(provider=>{const connection=cloudConnections.find(item=>item.provider===provider&&item.status==="connected");const label=provider==="google-drive"?"Google Drive":"OneDrive";return connection?<span className="pill" key={provider}><CheckCircle2 size={12}/>{label} · {connection.account}</span>:<a className="btn" key={provider} href={`/api/documents/connect/${provider==="google-drive"?"google":"microsoft"}/start`}>Anslut {label}</a>;})}</div></div>;
 const providerLabel=connectionProvider==="onedrive"?"OneDrive":"Google Drive";
 const resultCopy={connected:{title:`${providerLabel} är anslutet`,body:`Anslutningen är klar. Solvani kan nu använda de filer du aktivt väljer från ${providerLabel}.`},denied:{title:"Anslutningen avbröts",body:`Ingen åtkomst till ${providerLabel} gavs och inga filer har anslutits.`},invalid:{title:"Anslutningen kunde inte verifieras",body:`Säkerhetskontrollen för ${providerLabel} gick ut. Försök ansluta igen.`},failed:{title:"Anslutningen misslyckades",body:`${providerLabel} kunde inte kopplas just nu. Försök igen, eller kontrollera behörigheten.`},configuration:{title:`${providerLabel} behöver konfigureras`,body:"Anslutningen saknar en serverinställning. Ingen åtkomst har getts."}} as const;
 return <section className="document-vault">{connectionResult&&<div className="connection-result-overlay" role="dialog" aria-modal="true" aria-labelledby="document-connection-result"><div className={`connection-result-card ${connectionResult==="connected"?"success":"error"}`}>{connectionResult==="connected"?<CheckCircle2 size={22}/>:<XCircle size={22}/>}<div><span className="eyebrow">Documents & Media</span><h2 id="document-connection-result">{resultCopy[connectionResult].title}</h2><p>{resultCopy[connectionResult].body}</p></div><button className="btn primary" onClick={dismissConnectionResult}>Fortsätt</button></div></div>}{cloudActions}<div className="personal-context-head"><div><span className="eyebrow">Secure Document & Media Vault</span><h2>Viktiga dokument & media</h2><p>Dokument som AI bedömer har varaktigt värde kan sparas här och återanvändas vid framtida svar, vidarebefordran och uppgifter. Filerna ligger privat i Supabase Storage.</p></div><label className="btn primary"><Upload size={14}/> Importera vald fil<input hidden type="file" disabled={busy} onChange={e=>void upload(e.target.files?.[0])}/></label></div><div className="toolbar" aria-label="Filursprung"><label className="muted" htmlFor="vault-import-origin">Filursprung</label><select id="vault-import-origin" className="filter" value={origin} onChange={event=>setOrigin(event.target.value as ImportOrigin)} disabled={busy}><option value="device">Din enhet</option><option value="google_drive">Google Drive</option><option value="onedrive">OneDrive</option></select><small className="muted">Välj var filen kommer från. Solvani sparar en privat kopia och ändrar aldrig originalet.</small></div>{message&&<p className="assistant-notice">{message}</p>}{assets.length===0?<div className="empty-card">Inga sparade dokument ännu. Bilagor från anslutna konton och filer du väljer kan läggas i valvet.</div>:<div className="document-vault-grid">{assets.map(a=><article className="card document-vault-card" key={a.id}>{a.asset_kind==="document"?<FileText size={17}/>:<ImageIcon size={17}/>}<div><strong>{a.title||a.filename}</strong><small>{a.document_type||a.mime_type} · {a.external_origin?originLabel[a.external_origin]:a.source_type} · {Math.round(Number(a.importance_score||0)*100)}%</small></div>{a.summary&&<p>{a.summary}</p>}<div className="toolbar"><span className="pill">{a.sensitivity}</span>{a.reusable&&<span className="pill">Reusable</span>}<button className="btn" onClick={()=>void open(a.id)}><ExternalLink size={12}/> Öppna</button></div></article>)}</div>}</section>;
}
