"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Archive, Bell, Bolt, CheckCircle2, ChevronRight, CircleUserRound, Clock3, Command, Inbox, LayoutDashboard, Link2, LogOut, Mail, MessageCircle, MoreHorizontal, Network, Search, Send, Settings, Sparkles, Users, WandSparkles } from "lucide-react";
import { actionLabels, type CommunicationCase, type CommunicationPersonOption, type Conversation, type RecommendedAction, type SyncedEmailConversation, type UniversalCommunicationProfile } from "@/lib/domain";
import { cleanups, conversations, followUps, people } from "@/lib/mock-data";
import { signOut } from "@/app/auth/actions";
import { CommunicationCaseForm } from "@/components/communication-case-form";
import { analyzeEmailWithAI, correctEmailClassification } from "@/app/inbox/actions";
import { emailDashboardSummary, prioritizeEmails } from "@/lib/email-intelligence";
import { isRelevantEmail } from "@/lib/connectors/email-classification";
import { PersonaForm } from "@/components/persona-form";

type View = "today" | "cases" | "inbox" | "people" | "followups" | "cleanup" | "intelligence" | "connections" | "settings";
const navigation: { id: View; label: string; icon: typeof Inbox; count?: number }[] = [
  { id: "today", label: "Today", icon: LayoutDashboard }, { id: "cases", label: "Communication cases", icon: MessageCircle }, { id: "inbox", label: "Inbox", icon: Inbox }, { id: "people", label: "People", icon: Users }, { id: "followups", label: "Follow-ups", icon: Clock3 }, { id: "cleanup", label: "Clean Up", icon: Archive }, { id: "intelligence", label: "Intelligence", icon: Sparkles }, { id: "connections", label: "Connections", icon: Network }, { id: "settings", label: "Settings", icon: Settings },
];
const sources = ["Email", "Instagram", "WhatsApp", "Messenger", "Tinder", "TikTok", "LinkedIn"];
const EMAIL_CATEGORIES = ["Relevant", "Filtered out", "All categories", "Critical", "Action Required", "Business", "Customer", "Personal", "Booking / Travel", "Financial", "Legal", "Receipt / Invoice", "Newsletter", "Marketing", "Notification", "Spam", "Information Only"];

type MicrosoftConnection = {
  account_name: string | null;
  account_identifier: string | null;
  status: string;
  health_status: string;
  last_sync_at: string | null;
} | null;

export function Workspace({ userEmail, communicationCases, microsoftConnection, syncedEmails, persona, profilePeople }: { userEmail: string; communicationCases: CommunicationCase[]; microsoftConnection: MicrosoftConnection; syncedEmails: SyncedEmailConversation[]; persona: UniversalCommunicationProfile; profilePeople: CommunicationPersonOption[] }) {
  const router = useRouter();
  const automaticSyncStarted = useRef(false);
  const automaticAnalysisInFlight = useRef(false);
  const automaticAnalysisFailures = useRef(new Set<string>());
  const summary = emailDashboardSummary(syncedEmails);
  const [view, setView] = useState<View>("today");
  const [commandOpen, setCommandOpen] = useState(false);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setCommandOpen((open) => !open); } if (event.key === "Escape") setCommandOpen(false); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  useEffect(() => { if (!microsoftConnection || automaticSyncStarted.current) return; const lastSync = microsoftConnection.last_sync_at ? new Date(microsoftConnection.last_sync_at).getTime() : 0; if (Date.now() - lastSync < 5 * 60 * 1000) return; automaticSyncStarted.current = true; void fetch("/api/connectors/microsoft/sync", { method: "POST", headers: { "x-sync-trigger": "automatic" } }).then((response) => { if (response.ok) router.refresh(); }).catch(() => undefined); }, [microsoftConnection, router]);
  useEffect(() => { const next = syncedEmails.find((email) => email.messageId && isRelevantEmail(email.classification) && !email.analysis && !automaticAnalysisFailures.current.has(email.messageId)); if (!next || automaticAnalysisInFlight.current) return; automaticAnalysisInFlight.current = true; void analyzeEmailWithAI({ messageId: next.messageId, conversationId: next.id }).then((result) => { if (result.error) automaticAnalysisFailures.current.add(next.messageId); else router.refresh(); }).finally(() => { automaticAnalysisInFlight.current = false; }); }, [router, syncedEmails]);
  return <div className="workspace">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark"><Bolt size={15} /></span><span>Communication<br />Intelligence</span></div>
      <button className="command-button" onClick={() => setCommandOpen(true)}><Search size={13} /> Search or command <kbd>⌘K</kbd></button>
      <div className="nav-label">Workspace</div>
      {navigation.map((item) => <button key={item.id} className={`nav-button ${view === item.id ? "active" : ""}`} onClick={() => setView(item.id)}><item.icon size={15} />{item.label}{item.id === "inbox" && summary.unread > 0 && <span className="count">{summary.unread}</span>}</button>)}
      <div className="nav-label">Sources</div>
      {sources.map((source) => <button key={source} className="nav-button" onClick={() => setView("inbox")}><MessageCircle size={14} />{source}{source === "Email" && summary.total > 0 && <span className="count">{summary.total}</span>}</button>)}
      <div className="user-chip"><div className="avatar">ZV</div><div className="user-details"><strong>Zebastian</strong><br /><span className="muted" title={userEmail}>{userEmail}</span></div><form action={signOut}><button className="icon-button" type="submit" title="Sign out" aria-label="Sign out"><LogOut size={14} /></button></form></div>
    </aside>
    <main className="main">{view === "today" && <Today emails={syncedEmails.filter((email) => isRelevantEmail(email.classification))} onOpenInbox={() => setView("inbox")} />}{view === "cases" && <CommunicationCases cases={communicationCases} />}{view === "inbox" && <InboxView syncedEmails={syncedEmails} />}{view === "people" && <People />}{view === "followups" && <FollowUps />}{view === "cleanup" && <CleanUp />}{view === "intelligence" && <Intelligence />}{view === "connections" && <Connections microsoftConnection={microsoftConnection} />}{view === "settings" && <SettingsView persona={persona} people={profilePeople} />}</main>
    <nav className="mobile-bar">{navigation.slice(0, 4).map((item) => <button key={item.id} className={view === item.id ? "active" : ""} onClick={() => setView(item.id)}><item.icon size={17} />{item.label}</button>)}<button onClick={() => setView("settings")}><MoreHorizontal size={17} />More</button></nav>
    {commandOpen && <CommandBar close={() => setCommandOpen(false)} go={(next) => { setView(next); setCommandOpen(false); }} />}
  </div>;
}

function CommunicationCases({ cases }: { cases: CommunicationCase[] }) {
  return <div className="page"><PageHeader eyebrow="Supabase workspace" title="Communication cases" subtitle="Capture an important communication and keep it securely in your private workspace." />
    <div className="section-title"><MessageCircle size={14} color="#34d399" /> Create a new case</div>
    <CommunicationCaseForm />
    <div className="section-title">Saved cases <span className="count">{cases.length}</span></div>
    {cases.length === 0 ? <div className="empty-card">No cases saved yet. Use the form above to create the first one.</div> : <div className="case-list">{cases.map((item) => <article className="case-item" key={item.id}><div className="avatar">{item.personName.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase()}</div><div><div className="case-title"><strong>{item.title}</strong><span className="tag">{item.source}</span></div><span className="case-person">{item.personName} · {new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.createdAt))}</span><p>{item.message}</p></div></article>)}</div>}
  </div>;
}

function Today({ emails, onOpenInbox }: { emails: SyncedEmailConversation[]; onOpenInbox: () => void }) {
  const ordered = prioritizeEmails(emails);
  const summary = emailDashboardSummary(emails);
  const critical = ordered.filter((email) => email.classification === "Critical");
  const respond = ordered.filter((email) => ["RESPOND_NOW", "RESPOND_TODAY", "RESPOND_LATER"].includes(email.recommendedAction) && email.classification !== "Critical");
  const lowAttention = ordered.filter((email) => email.priorityScore < 4);
  return <div className="page"><span className="eyebrow">Live Outlook intelligence</span><h1>Your communication today</h1><p className="subtitle">{emails.length > 0 ? <>You have <strong style={{color:"white"}}>{summary.needsResponse} conversations</strong> that may need a response.</> : "Import Outlook messages to replace the empty dashboard with live communication."}</p>
    <div className="summary-bar"><div className="summary-stat"><strong>{summary.unread}</strong><span>unread</span></div><div className="summary-stat"><strong>{summary.needsResponse}</strong><span>may need response</span></div><div className="summary-stat"><strong>{summary.critical}</strong><span>critical</span></div><div className="summary-stat"><strong>{summary.lowAttention}</strong><span>low attention</span></div></div>
    {emails.length === 0 && <div className="empty-card">No synchronized Outlook messages yet. Open Connections and run the first import.</div>}
    {critical.length > 0 && <><div className="section-title"><Bell size={14} color="#fb7185" /> Critical <span className="count">{critical.length}</span></div><div className="cards">{critical.slice(0, 3).map((email) => <LiveEmailCard key={email.id} email={email} onClick={onOpenInbox} />)}</div></>}
    {respond.length > 0 && <><div className="section-title"><MessageCircle size={14} color="#34d399" /> Respond <span className="count">{respond.length}</span></div><div className="cards">{respond.slice(0, 3).map((email) => <LiveEmailCard key={email.id} email={email} onClick={onOpenInbox} />)}</div></>}
    {lowAttention.length > 0 && <><div className="section-title"><Archive size={14} color="#8b939f" /> Low attention <span className="count">{lowAttention.length}</span></div><div className="cards">{lowAttention.slice(0, 3).map((email) => <LiveEmailCard key={email.id} email={email} onClick={onOpenInbox} />)}</div></>}
  </div>;
}

function LiveEmailCard({ email, onClick }: { email: SyncedEmailConversation; onClick: () => void }) { const action = actionLabels[email.recommendedAction as RecommendedAction] ?? email.recommendedAction; return <button className="card" onClick={onClick} style={{textAlign:"left",cursor:"pointer"}}><div className="card-top"><span>{email.title}</span><span className="score">{email.priorityScore}</span></div><div className="card-person"><div className="avatar">{email.personName.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase()}</div><div><strong>{email.personName}</strong><span>{email.classification}</span></div></div><p>{email.preview}</p><span className="pill">{action} <ChevronRight size={10} /></span></button> }

function ConversationCard({ conversation, onClick }: { conversation: Conversation; onClick: () => void }) { return <button className="card" onClick={onClick} style={{textAlign:"left",cursor:"pointer"}}><div className="card-top"><span>{conversation.subject}</span><span className="score">{conversation.attention.score}</span></div><div className="card-person"><div className="avatar">{conversation.person.initials}</div><div><strong>{conversation.person.name}</strong><span>{conversation.person.organization ?? conversation.person.role}</span></div></div><p>{conversation.preview}</p><span className="pill">{actionLabels[conversation.action]} <ChevronRight size={10} /></span></button> }

function InboxView({ syncedEmails }: { syncedEmails: SyncedEmailConversation[] }) {
  if (syncedEmails.length > 0) return <SyncedInbox emails={syncedEmails} />;
  return <div className="page"><PageHeader eyebrow="Live Outlook inbox" title="Inbox" subtitle="Synchronized Outlook conversations will appear here." /><div className="empty-card">No Outlook messages have been synchronized yet. Open Connections and run the first import.</div></div>;
}

function MockInbox() {
  const [selectedId, setSelectedId] = useState(conversations[0].id); const selected = conversations.find((item) => item.id === selectedId) ?? conversations[0];
  const [draft, setDraft] = useState(selected.draft ?? "");
  return <div className="inbox"><section className="inbox-col"><div className="inbox-head"><h1>Inbox</h1><button className="filter">Smart ▾</button></div>{conversations.map((conversation) => <div key={conversation.id} className={`conversation-row ${selected.id === conversation.id ? "selected" : ""}`} onClick={() => { setSelectedId(conversation.id); setDraft(conversation.draft ?? ""); }}><div className="avatar">{conversation.person.initials}</div><div><strong>{conversation.person.name}</strong><p>{conversation.preview}</p></div><div className="row-meta">{conversation.timestamp}<div className="row-score">{conversation.attention.score}</div></div></div>)}</section>
    <section className="inbox-col thread"><div className="thread-head"><strong>{selected.person.name}</strong><span>{selected.subject} · {selected.person.sources.join(" + ")}</span></div><div className="messages">{selected.messages.map((message) => <div key={message.id} className={`message ${message.direction === "out" ? "out" : ""}`}><div className="message-bubble">{message.body}</div><div className="message-meta">{message.source} · {message.timestamp}</div></div>)}</div><div className="composer"><textarea aria-label="Reply draft" value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Write a reply…" /><div className="composer-actions"><button className="btn" onClick={() => setDraft(selected.draft ?? "Thanks — I’ll get back to you shortly.")}><WandSparkles size={11} style={{display:"inline",marginRight:5}} />Generate</button><button className="btn primary" disabled={!draft}>Review send</button></div></div></section>
    <aside className="intel"><h2>AI Intelligence</h2><div className="intel-section"><div className="intel-label">Person</div><div className="card-person" style={{margin:0}}><div className="avatar">{selected.person.initials}</div><div><strong>{selected.person.name}</strong><span>{selected.person.role} · {selected.person.priority} priority</span></div></div></div><div className="intel-section"><div className="intel-label">Assessment</div><p>{selected.actionReason}</p></div><div className="intel-section"><div style={{display:"flex",justifyContent:"space-between"}}><div className="intel-label">Attention</div><strong style={{color:"#86efc2"}}>{selected.attention.score}/10</strong></div>{selected.attention.dimensions.map((dimension) => <div className="dimension" key={dimension.label}><span title={dimension.reason}>{dimension.label}</span><b className={dimension.value >= 0 ? "positive" : "negative"}>{dimension.value > 0 ? "+" : ""}{dimension.value.toFixed(1)}</b></div>)}</div><div className="intel-section"><div className="intel-label">Recommended action</div><span className="pill" style={{marginTop:0}}>{actionLabels[selected.action]}</span></div>{selected.openLoop && <div className="intel-section"><div className="intel-label">Open loop</div><p><CheckCircle2 size={12} style={{display:"inline",marginRight:6}} />{selected.openLoop}</p></div>}<div className="intel-section"><div className="intel-label">Draft response</div>{selected.draft ? <><div className="draft">{selected.draft}</div><div className="toolbar"><button className="btn">Shorter</button><button className="btn">Warmer</button><button className="btn">Direct</button><button className="btn" onClick={() => setDraft(selected.draft ?? "")}>Use draft</button></div></> : <button className="btn" onClick={() => setDraft("Thanks for reaching out. I’ll review this and get back to you.")}>Generate draft</button>}</div></aside></div>;
}

function SyncedInbox({ emails }: { emails: SyncedEmailConversation[] }) {
  const router = useRouter();
  const [category, setCategory] = useState("Relevant");
  const [selectedId, setSelectedId] = useState(emails[0].id);
  const [savingCategory, setSavingCategory] = useState(false);
  const [categoryError, setCategoryError] = useState("");
  const [analyzing, setAnalyzing] = useState(false);
  const [analysisError, setAnalysisError] = useState("");
  const [replyDrafts, setReplyDrafts] = useState<Record<string, string>>({});
  const [confirmSendId, setConfirmSendId] = useState("");
  const [sending, setSending] = useState(false);
  const [sendMessage, setSendMessage] = useState("");
  const filtered = prioritizeEmails(category === "All categories" ? emails : category === "Relevant" ? emails.filter((email) => isRelevantEmail(email.classification)) : category === "Filtered out" ? emails.filter((email) => !isRelevantEmail(email.classification)) : emails.filter((email) => email.classification === category));
  const selected = filtered.find((email) => email.id === selectedId) ?? filtered[0];
  if (!selected) return <div className="page"><PageHeader eyebrow="Live Outlook inbox" title="Inbox" subtitle="Filter synchronized messages by category." /><div className="inbox-head"><select className="filter" aria-label="Email category" value={category} onChange={(event) => setCategory(event.target.value)}>{EMAIL_CATEGORIES.map((item) => <option key={item}>{item}</option>)}</select></div><div className="empty-card">No messages match this category.</div></div>;
  const replyDraft = replyDrafts[selected.id] ?? selected.analysis?.draftResponse ?? "";
  const setReplyDraft = (value: string) => setReplyDrafts((drafts) => ({ ...drafts, [selected.id]: value }));
  const action = actionLabels[selected.recommendedAction as RecommendedAction] ?? selected.recommendedAction;
  const selectEmail = (id: string) => { setSelectedId(id); setAnalysisError(""); setConfirmSendId(""); setSendMessage(""); };
  const saveCategory = async (classification: string) => { setSavingCategory(true); setCategoryError(""); const result = await correctEmailClassification({ messageId: selected.messageId, conversationId: selected.id, classification }); if (result.error) setCategoryError(result.error); else router.refresh(); setSavingCategory(false); };
  const analyze = async () => { setAnalyzing(true); setAnalysisError(""); const result = await analyzeEmailWithAI({ messageId: selected.messageId, conversationId: selected.id }); if (result.error) setAnalysisError(result.error); else router.refresh(); setAnalyzing(false); };
  const sendReply = async () => { setSending(true); setSendMessage(""); try { const response = await fetch("/api/connectors/microsoft/reply", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ messageId: selected.messageId, conversationId: selected.id, body: replyDraft }) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error ?? "The reply could not be sent."); setSendMessage("Reply sent through Outlook."); setConfirmSendId(""); router.refresh(); } catch (error) { setSendMessage(error instanceof Error ? error.message : "The reply could not be sent."); } finally { setSending(false); } };

  return <div className="inbox">
    <section className="inbox-col"><div className="inbox-head"><h1>Inbox</h1><select className="filter" aria-label="Email category" value={category} onChange={(event) => setCategory(event.target.value)}>{EMAIL_CATEGORIES.map((item) => <option key={item}>{item}</option>)}</select></div>{filtered.map((email) => <div key={email.id} className={`conversation-row ${selected.id === email.id ? "selected" : ""}`} onClick={() => selectEmail(email.id)}><div className="avatar">{email.personName.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase()}</div><div><strong>{email.personName}{email.unread ? " · New" : ""}</strong><p>{email.title}</p></div><div className="row-meta">{new Intl.DateTimeFormat("en", { month: "short", day: "numeric" }).format(new Date(email.receivedAt))}<div className="row-score">{email.priorityScore}</div></div></div>)}</section>
    <section className="inbox-col thread"><div className="thread-head"><strong>{selected.personName}</strong><span>{selected.title} · Outlook</span></div><div className="messages"><div className="message"><div className="message-bubble">{selected.preview || "No text preview is available for this message."}</div><div className="message-meta">Outlook · {new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(selected.receivedAt))}</div></div></div></section>
    <aside className="intel"><h2>Communication Intelligence</h2>
      <div className="intel-section"><div className="intel-label">Category</div><select className="filter" aria-label="Correct email category" value={selected.classification} disabled={savingCategory} onChange={(event) => void saveCategory(event.target.value)}>{EMAIL_CATEGORIES.slice(3).map((item) => <option key={item}>{item}</option>)}</select>{categoryError && <p className="negative">{categoryError}</p>}</div>
      <div className="intel-section"><div className="intel-label">Priority</div><strong style={{color:"#86efc2"}}>{selected.priorityScore}/10</strong></div><div className="intel-section"><div className="intel-label">Recommended action</div><span className="pill">{action}</span></div>
      {selected.analysis ? <><div className="intel-section"><div className="intel-label">AI summary · {Math.round(selected.analysis.confidence * 100)}% confidence</div><p>{selected.analysis.summary}</p></div><div className="intel-section"><div className="intel-label">Intent</div><p>{selected.analysis.intent}</p><small className="muted">{selected.analysis.priorityReason}</small></div>
        <div className="intel-section reply-section"><div className="reply-heading"><div><span>Suggested reply</span><small>{selected.analysis.draftTone}</small></div><WandSparkles size={18} /></div>{selected.analysis.requiresReply && replyDraft ? <><textarea aria-label="Editable suggested reply" value={replyDraft} onChange={(event) => { setReplyDraft(event.target.value); setConfirmSendId(""); setSendMessage(""); }} /><div className="reply-help">Review and edit the text before sending it through Outlook.</div>{confirmSendId === selected.id ? <div className="send-confirm"><strong>Send this reply to {selected.personName}?</strong><div><button className="btn" type="button" onClick={() => setConfirmSendId("")} disabled={sending}>Cancel</button><button className="btn send-button" type="button" onClick={() => void sendReply()} disabled={sending}>{sending ? "Sending…" : <><Send size={13} /> Yes, send now</>}</button></div></div> : <button className="btn send-button send-button-main" type="button" onClick={() => setConfirmSendId(selected.id)} disabled={!replyDraft.trim()}><Send size={14} /> Review & send reply</button>}{sendMessage && <p className={sendMessage.startsWith("Reply sent") ? "positive" : "negative"}>{sendMessage}</p>}</> : <p>No reply is recommended for this message.</p>}</div>
        {selected.analysis.commitment && <div className="intel-section"><div className="intel-label">Suggested commitment — review only</div><p>{selected.analysis.commitment.description}</p>{selected.analysis.commitment.dueAt && <small className="muted">Due: {selected.analysis.commitment.dueAt}</small>}</div>}</> : <div className="intel-section"><p>Waiting for automatic analysis. The selected email and limited writing-style examples are sent securely to OpenAI. Nothing is sent to the recipient.</p></div>}
      <div className="intel-section"><button className="btn" onClick={analyze} disabled={analyzing}>{analyzing ? "Analyzing…" : selected.analysis ? "Generate a new analysis and reply" : "Analyze now"}</button>{analysisError && <p className="negative">{analysisError}</p>}</div>
    </aside>
  </div>;
}

function PageHeader({ eyebrow, title, subtitle }: { eyebrow: string; title: string; subtitle: string }) { return <><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p className="subtitle">{subtitle}</p></> }
function People() { return <div className="page"><PageHeader eyebrow="Personal CRM" title="People" subtitle="Relationships unified across every communication source." /><div className="summary-bar"><div className="summary-stat"><strong>184</strong><span>people</span></div><div className="summary-stat"><strong>12</strong><span>high priority</span></div><div className="summary-stat"><strong>4</strong><span>identity matches to review</span></div></div><div className="list">{people.map((person) => <div className="list-row" key={person.id}><div className="avatar">{person.initials}</div><div><strong>{person.name}</strong><small>{person.role}{person.organization ? ` · ${person.organization}` : ""}</small></div><div className="muted">{person.summary}</div><div><span className="tag">{person.sources.join(" · ")}</span><small>{person.lastContact}</small></div></div>)}</div></div> }
function FollowUps() { return <div className="page"><PageHeader eyebrow="Open loops" title="Follow-ups" subtitle="Promises, requests, and commitments that should not slip." /><div className="summary-bar"><div className="summary-stat"><strong>2</strong><span>I owe them</span></div><div className="summary-stat"><strong>1</strong><span>they owe me</span></div><div className="summary-stat"><strong>1</strong><span>due today</span></div></div><div className="list">{followUps.map((item) => <div className="list-row" key={item.text}><div className="avatar"><Clock3 size={14} /></div><div><strong>{item.person}</strong><small>{item.owner}</small></div><div>{item.text}</div><div className={item.tone === "urgent" ? "negative" : "muted"}>{item.due}</div></div>)}</div></div> }
function CleanUp() { const [approved, setApproved] = useState<string[]>([]); return <div className="page"><PageHeader eyebrow="Email hygiene" title="Clean Up" subtitle="Review low-value senders before anything destructive happens." /><div className="summary-bar"><div className="summary-stat"><strong>25</strong><span>suggested unsubscribes</span></div><div className="summary-stat"><strong>47</strong><span>marketing to archive</span></div><div className="summary-stat"><strong>84</strong><span>old notifications</span></div></div><div className="section-title">Suggested cleanups</div><div className="list">{cleanups.map((item) => <div className="list-row" key={item.sender}><div className="avatar"><Mail size={14} /></div><div><strong>{item.sender}</strong><small>{item.count} messages</small></div><div className="muted">{item.reason}</div><div><button className="btn" onClick={() => setApproved((values) => values.includes(item.sender) ? values.filter((value) => value !== item.sender) : [...values, item.sender])}>{approved.includes(item.sender) ? "Selected" : item.action}</button></div></div>)}</div>{approved.length > 0 && <div style={{marginTop:14,display:"flex",justifyContent:"flex-end",gap:8}}><button className="btn" onClick={() => setApproved([])}>Cancel</button><button className="btn primary">Review {approved.length} action{approved.length > 1 ? "s" : ""}</button></div>}</div> }
function Intelligence() { return <div className="page"><PageHeader eyebrow="Preference brain" title="Intelligence" subtitle="Transparent signals shaping what deserves your attention." /><div className="cards"><div className="card"><div className="intel-label">Communication</div><h3>Concise by default</h3><p>Drafts average 3–5 sentences. Business communication is direct and warm.</p><span className="pill">12 learned preferences</span></div><div className="card"><div className="intel-label">Business</div><h3>Strategic partnerships</h3><p>Founder relationships and concrete product opportunities receive higher weight.</p><span className="pill">8 priority signals</span></div><div className="card"><div className="intel-label">Inbox</div><h3>Protect trusted senders</h3><p>Financial, legal, travel, and security messages are never suggested for automatic deletion.</p><span className="pill">7 safety rules</span></div></div></div> }
function Connections({ microsoftConnection }: { microsoftConnection: MicrosoftConnection }) { const router = useRouter(); const [syncing, setSyncing] = useState(false); const [syncError, setSyncError] = useState(""); const [syncResult, setSyncResult] = useState(""); const account = microsoftConnection?.account_name ?? microsoftConnection?.account_identifier; const sync = async () => { setSyncing(true); setSyncError(""); setSyncResult(""); try { const response = await fetch("/api/connectors/microsoft/sync", { method: "POST" }); const result = await response.json() as { imported?: number; error?: string }; if (!response.ok) throw new Error(result.error ?? "The import failed."); setSyncResult(`${result.imported ?? 0} Outlook messages imported. Open Inbox to review them.`); router.refresh(); } catch (error) { setSyncError(error instanceof Error ? error.message : "The import failed."); } finally { setSyncing(false); } }; return <div className="page"><PageHeader eyebrow="Sources" title="Connections" subtitle="Provider integrations are capability-aware and require your approval." />{syncResult && <div className="empty-card">{syncResult}</div>}<div className="list"><div className="list-row"><div className="avatar"><Link2 size={14} /></div><div><strong>Outlook & Microsoft 365</strong><small>{account ?? "Personal, work, and school accounts"}</small></div><div className="muted">{microsoftConnection ? "Connected securely with Microsoft" : "Connect securely with Microsoft"}{syncError && <small className="negative">{syncError}</small>}</div><div>{microsoftConnection ? <div style={{display:"flex",gap:8,alignItems:"center"}}><span className="pill"><CheckCircle2 size={11} /> Connected</span><button className="btn" onClick={sync} disabled={syncing}>{syncing ? "Importing…" : "Import messages"}</button></div> : <a className="btn" href="/api/connectors/microsoft/start">Connect Outlook</a>}</div></div>{["Gmail", "Manual capture", "Instagram", "WhatsApp"].map((name, index) => <div className="list-row" key={name}><div className="avatar"><Link2 size={14} /></div><div><strong>{name}</strong><small>{index === 1 ? "Available" : "Feature flagged"}</small></div><div className="muted">{index === 1 ? "Paste and verify conversations" : "No account connected"}</div><div><button className="btn" disabled={index !== 1}>{index === 1 ? "Open" : "Coming later"}</button></div></div>)}</div></div> }
function SettingsView({ persona, people }: { persona: UniversalCommunicationProfile; people: CommunicationPersonOption[] }) { return <div className="page"><PageHeader eyebrow="Private workspace" title="Universal communication profile" subtitle="One profile for how you communicate across people, situations and apps." /><div className="section-title"><Sparkles size={14} /> Your verified communication rules</div><p className="subtitle">You control every saved fact. Priority: person and situation first, then channel, then your core profile.</p><PersonaForm initial={persona} people={people} /><div className="cards"><div className="card"><CircleUserRound size={17} /><h3>Account & security</h3><p>Supabase Auth architecture with manual provisioning and mandatory TOTP MFA.</p><span className="pill">MFA required</span></div><div className="card"><Sparkles size={17} /><h3>AI & privacy</h3><p>Only the relevant channel, situation and person profile is sent for the active message.</p><span className="pill">Minimal context</span></div><div className="card"><CheckCircle2 size={17} /><h3>Profile control</h3><p>AI can use your profile but cannot change it or turn an inference into a saved fact.</p><span className="pill">Owner verified</span></div></div></div> }
function CommandBar({ close, go }: { close: () => void; go: (view: View) => void }) { const [query, setQuery] = useState(""); const items = useMemo(() => [{text:"Who do I need to answer today?",view:"today" as View},{text:"Show my smart inbox",view:"inbox" as View},{text:"Show people I promised to contact",view:"followups" as View},{text:"Review low-value newsletters",view:"cleanup" as View}].filter((item) => item.text.toLowerCase().includes(query.toLowerCase())),[query]); return <div className="command-overlay" onMouseDown={close}><div className="command" onMouseDown={(event) => event.stopPropagation()}><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Ask about your communication…" /><div className="command-list">{items.map((item) => <div className="command-item" key={item.text} onClick={() => go(item.view)}><Command size={12} style={{display:"inline",marginRight:8}} />{item.text}</div>)}</div></div></div> }
