"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Archive, Bell, Bolt, CheckCircle2, ChevronRight, CircleUserRound, Clock3, Command, Inbox, LayoutDashboard, Link2, LogOut, Mail, MessageCircle, MoreHorizontal, Network, Search, Settings, Sparkles, Users, WandSparkles } from "lucide-react";
import { actionLabels, type CommunicationCase, type Conversation, type RecommendedAction, type SyncedEmailConversation } from "@/lib/domain";
import { cleanups, conversations, followUps, people } from "@/lib/mock-data";
import { signOut } from "@/app/auth/actions";
import { CommunicationCaseForm } from "@/components/communication-case-form";

type View = "today" | "cases" | "inbox" | "people" | "followups" | "cleanup" | "intelligence" | "connections" | "settings";
const navigation: { id: View; label: string; icon: typeof Inbox; count?: number }[] = [
  { id: "today", label: "Today", icon: LayoutDashboard }, { id: "cases", label: "Communication cases", icon: MessageCircle }, { id: "inbox", label: "Inbox", icon: Inbox, count: 12 }, { id: "people", label: "People", icon: Users }, { id: "followups", label: "Follow-ups", icon: Clock3, count: 3 }, { id: "cleanup", label: "Clean Up", icon: Archive, count: 25 }, { id: "intelligence", label: "Intelligence", icon: Sparkles }, { id: "connections", label: "Connections", icon: Network }, { id: "settings", label: "Settings", icon: Settings },
];
const sources = [{ name: "Email", count: 8 }, { name: "Instagram", count: 2 }, { name: "WhatsApp", count: 2 }, { name: "Messenger" }, { name: "Tinder" }, { name: "TikTok" }, { name: "LinkedIn" }];

type MicrosoftConnection = {
  account_name: string | null;
  account_identifier: string | null;
  status: string;
  health_status: string;
} | null;

export function Workspace({ userEmail, communicationCases, microsoftConnection, syncedEmails }: { userEmail: string; communicationCases: CommunicationCase[]; microsoftConnection: MicrosoftConnection; syncedEmails: SyncedEmailConversation[] }) {
  const [view, setView] = useState<View>("today");
  const [commandOpen, setCommandOpen] = useState(false);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setCommandOpen((open) => !open); } if (event.key === "Escape") setCommandOpen(false); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  return <div className="workspace">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark"><Bolt size={15} /></span><span>Communication<br />Intelligence</span></div>
      <button className="command-button" onClick={() => setCommandOpen(true)}><Search size={13} /> Search or command <kbd>⌘K</kbd></button>
      <div className="nav-label">Workspace</div>
      {navigation.map((item) => <button key={item.id} className={`nav-button ${view === item.id ? "active" : ""}`} onClick={() => setView(item.id)}><item.icon size={15} />{item.label}{item.count && <span className="count">{item.count}</span>}</button>)}
      <div className="nav-label">Sources</div>
      {sources.map((source) => <button key={source.name} className="nav-button" onClick={() => setView("inbox")}><MessageCircle size={14} />{source.name}{source.count && <span className="count">{source.count}</span>}</button>)}
      <div className="user-chip"><div className="avatar">ZV</div><div className="user-details"><strong>Zebastian</strong><br /><span className="muted" title={userEmail}>{userEmail}</span></div><form action={signOut}><button className="icon-button" type="submit" title="Sign out" aria-label="Sign out"><LogOut size={14} /></button></form></div>
    </aside>
    <main className="main">{view === "today" && <Today onOpenInbox={() => setView("inbox")} />}{view === "cases" && <CommunicationCases cases={communicationCases} />}{view === "inbox" && <InboxView syncedEmails={syncedEmails} />}{view === "people" && <People />}{view === "followups" && <FollowUps />}{view === "cleanup" && <CleanUp />}{view === "intelligence" && <Intelligence />}{view === "connections" && <Connections microsoftConnection={microsoftConnection} />}{view === "settings" && <SettingsView />}</main>
    <nav className="mobile-bar">{navigation.slice(0, 4).map((item) => <button key={item.id} className={view === item.id ? "active" : ""} onClick={() => setView(item.id)}><item.icon size={17} />{item.label}</button>)}<button onClick={() => setView("settings")}><MoreHorizontal size={17} />More</button></nav>
    {commandOpen && <CommandBar close={() => setCommandOpen(false)} go={(next) => { setView(next); setCommandOpen(false); }} />}
  </div>;
}

function CommunicationCases({ cases }: { cases: CommunicationCase[] }) {
  return <div className="page"><PageHeader eyebrow="Supabase workspace" title="Communication cases" subtitle="Capture an important communication and keep it securely in your private workspace." />
    <div className="section-title"><MessageCircle size={14} color="#34d399" /> Create a new case</div>
    <CommunicationCaseForm />
    <div className="section-title">Saved cases <span className="count">{cases.length}</span></div>
    {cases.length === 0 ? <div className="empty-card">No cases saved yet. Use the form above to create the first one.</div> : <div className="case-list">{cases.map((item) => <article className="case-item" key={item.id}><div className="avatar">{item.personName.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase()}</div><div><div className="case-title"><strong>{item.title}</strong><span className="tag">{item.source}</span></div><span className="case-person">{item.personName} · {new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.createdAt))}</span><p>{item.message}</p></div></article>)}</div>}
  </div>;
}

function Today({ onOpenInbox }: { onOpenInbox: () => void }) {
  return <div className="page"><span className="eyebrow">Saturday, 29 August</span><h1>Good evening, Zebastian</h1><p className="subtitle">You have <strong style={{color:"white"}}>6 conversations</strong> worth your attention.</p>
    <div className="summary-bar"><div className="summary-stat"><strong>73</strong><span>new communications</span></div><div className="summary-stat"><strong>6</strong><span>worth attention</span></div><div className="summary-stat"><strong>3</strong><span>drafts ready</span></div><div className="summary-grow"><div style={{display:"flex",justifyContent:"space-between",fontSize:11}}><span>Today&apos;s communication load</span><span className="muted">~12 min focused</span></div><div className="progress"><span /></div></div></div>
    <div className="section-title"><Bell size={14} color="#fb7185" /> Critical & decisions <span className="count">1</span></div><div className="cards"><ConversationCard conversation={conversations[0]} onClick={onOpenInbox} /></div>
    <div className="section-title"><MessageCircle size={14} color="#34d399" /> Respond <span className="count">2</span></div><div className="cards">{conversations.slice(1,3).map((conversation) => <ConversationCard key={conversation.id} conversation={conversation} onClick={onOpenInbox} />)}</div>
    <div className="section-title"><Archive size={14} color="#8b939f" /> Can ignore <span className="count">1</span></div><div className="cards"><ConversationCard conversation={conversations[3]} onClick={onOpenInbox} /></div>
  </div>;
}

function ConversationCard({ conversation, onClick }: { conversation: Conversation; onClick: () => void }) { return <button className="card" onClick={onClick} style={{textAlign:"left",cursor:"pointer"}}><div className="card-top"><span>{conversation.subject}</span><span className="score">{conversation.attention.score}</span></div><div className="card-person"><div className="avatar">{conversation.person.initials}</div><div><strong>{conversation.person.name}</strong><span>{conversation.person.organization ?? conversation.person.role}</span></div></div><p>{conversation.preview}</p><span className="pill">{actionLabels[conversation.action]} <ChevronRight size={10} /></span></button> }

function InboxView({ syncedEmails }: { syncedEmails: SyncedEmailConversation[] }) {
  if (syncedEmails.length > 0) return <SyncedInbox emails={syncedEmails} />;
  return <MockInbox />;
}

function MockInbox() {
  const [selectedId, setSelectedId] = useState(conversations[0].id); const selected = conversations.find((item) => item.id === selectedId) ?? conversations[0];
  const [draft, setDraft] = useState(selected.draft ?? "");
  return <div className="inbox"><section className="inbox-col"><div className="inbox-head"><h1>Inbox</h1><button className="filter">Smart ▾</button></div>{conversations.map((conversation) => <div key={conversation.id} className={`conversation-row ${selected.id === conversation.id ? "selected" : ""}`} onClick={() => { setSelectedId(conversation.id); setDraft(conversation.draft ?? ""); }}><div className="avatar">{conversation.person.initials}</div><div><strong>{conversation.person.name}</strong><p>{conversation.preview}</p></div><div className="row-meta">{conversation.timestamp}<div className="row-score">{conversation.attention.score}</div></div></div>)}</section>
    <section className="inbox-col thread"><div className="thread-head"><strong>{selected.person.name}</strong><span>{selected.subject} · {selected.person.sources.join(" + ")}</span></div><div className="messages">{selected.messages.map((message) => <div key={message.id} className={`message ${message.direction === "out" ? "out" : ""}`}><div className="message-bubble">{message.body}</div><div className="message-meta">{message.source} · {message.timestamp}</div></div>)}</div><div className="composer"><textarea aria-label="Reply draft" value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Write a reply…" /><div className="composer-actions"><button className="btn" onClick={() => setDraft(selected.draft ?? "Thanks — I’ll get back to you shortly.")}><WandSparkles size={11} style={{display:"inline",marginRight:5}} />Generate</button><button className="btn primary" disabled={!draft}>Review send</button></div></div></section>
    <aside className="intel"><h2>AI Intelligence</h2><div className="intel-section"><div className="intel-label">Person</div><div className="card-person" style={{margin:0}}><div className="avatar">{selected.person.initials}</div><div><strong>{selected.person.name}</strong><span>{selected.person.role} · {selected.person.priority} priority</span></div></div></div><div className="intel-section"><div className="intel-label">Assessment</div><p>{selected.actionReason}</p></div><div className="intel-section"><div style={{display:"flex",justifyContent:"space-between"}}><div className="intel-label">Attention</div><strong style={{color:"#86efc2"}}>{selected.attention.score}/10</strong></div>{selected.attention.dimensions.map((dimension) => <div className="dimension" key={dimension.label}><span title={dimension.reason}>{dimension.label}</span><b className={dimension.value >= 0 ? "positive" : "negative"}>{dimension.value > 0 ? "+" : ""}{dimension.value.toFixed(1)}</b></div>)}</div><div className="intel-section"><div className="intel-label">Recommended action</div><span className="pill" style={{marginTop:0}}>{actionLabels[selected.action]}</span></div>{selected.openLoop && <div className="intel-section"><div className="intel-label">Open loop</div><p><CheckCircle2 size={12} style={{display:"inline",marginRight:6}} />{selected.openLoop}</p></div>}<div className="intel-section"><div className="intel-label">Draft response</div>{selected.draft ? <><div className="draft">{selected.draft}</div><div className="toolbar"><button className="btn">Shorter</button><button className="btn">Warmer</button><button className="btn">Direct</button><button className="btn" onClick={() => setDraft(selected.draft ?? "")}>Use draft</button></div></> : <button className="btn" onClick={() => setDraft("Thanks for reaching out. I’ll review this and get back to you.")}>Generate draft</button>}</div></aside></div>;
}

function SyncedInbox({ emails }: { emails: SyncedEmailConversation[] }) {
  const [selectedId, setSelectedId] = useState(emails[0].id);
  const selected = emails.find((email) => email.id === selectedId) ?? emails[0];
  const action = actionLabels[selected.recommendedAction as RecommendedAction] ?? selected.recommendedAction;
  return <div className="inbox"><section className="inbox-col"><div className="inbox-head"><h1>Inbox</h1><span className="pill">Outlook · {emails.length}</span></div>{emails.map((email) => <div key={email.id} className={`conversation-row ${selected.id === email.id ? "selected" : ""}`} onClick={() => setSelectedId(email.id)}><div className="avatar">{email.personName.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase()}</div><div><strong>{email.personName}{email.unread ? " · New" : ""}</strong><p>{email.title}</p></div><div className="row-meta">{new Intl.DateTimeFormat("en", { month: "short", day: "numeric" }).format(new Date(email.receivedAt))}<div className="row-score">{email.priorityScore}</div></div></div>)}</section><section className="inbox-col thread"><div className="thread-head"><strong>{selected.personName}</strong><span>{selected.title} · Outlook</span></div><div className="messages"><div className="message"><div className="message-bubble">{selected.preview || "No text preview is available for this message."}</div><div className="message-meta">Outlook · {new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(selected.receivedAt))}</div></div></div></section><aside className="intel"><h2>Communication Intelligence</h2><div className="intel-section"><div className="intel-label">Initial category</div><span className="pill">{selected.classification}</span></div><div className="intel-section"><div className="intel-label">Priority</div><strong style={{color:"#86efc2"}}>{selected.priorityScore}/10</strong></div><div className="intel-section"><div className="intel-label">Recommended action</div><span className="pill">{action}</span></div><div className="intel-section"><p>Initial categories use transparent rules. AI refinement and feedback learning are added in a later phase.</p></div></aside></div>;
}

function PageHeader({ eyebrow, title, subtitle }: { eyebrow: string; title: string; subtitle: string }) { return <><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p className="subtitle">{subtitle}</p></> }
function People() { return <div className="page"><PageHeader eyebrow="Personal CRM" title="People" subtitle="Relationships unified across every communication source." /><div className="summary-bar"><div className="summary-stat"><strong>184</strong><span>people</span></div><div className="summary-stat"><strong>12</strong><span>high priority</span></div><div className="summary-stat"><strong>4</strong><span>identity matches to review</span></div></div><div className="list">{people.map((person) => <div className="list-row" key={person.id}><div className="avatar">{person.initials}</div><div><strong>{person.name}</strong><small>{person.role}{person.organization ? ` · ${person.organization}` : ""}</small></div><div className="muted">{person.summary}</div><div><span className="tag">{person.sources.join(" · ")}</span><small>{person.lastContact}</small></div></div>)}</div></div> }
function FollowUps() { return <div className="page"><PageHeader eyebrow="Open loops" title="Follow-ups" subtitle="Promises, requests, and commitments that should not slip." /><div className="summary-bar"><div className="summary-stat"><strong>2</strong><span>I owe them</span></div><div className="summary-stat"><strong>1</strong><span>they owe me</span></div><div className="summary-stat"><strong>1</strong><span>due today</span></div></div><div className="list">{followUps.map((item) => <div className="list-row" key={item.text}><div className="avatar"><Clock3 size={14} /></div><div><strong>{item.person}</strong><small>{item.owner}</small></div><div>{item.text}</div><div className={item.tone === "urgent" ? "negative" : "muted"}>{item.due}</div></div>)}</div></div> }
function CleanUp() { const [approved, setApproved] = useState<string[]>([]); return <div className="page"><PageHeader eyebrow="Email hygiene" title="Clean Up" subtitle="Review low-value senders before anything destructive happens." /><div className="summary-bar"><div className="summary-stat"><strong>25</strong><span>suggested unsubscribes</span></div><div className="summary-stat"><strong>47</strong><span>marketing to archive</span></div><div className="summary-stat"><strong>84</strong><span>old notifications</span></div></div><div className="section-title">Suggested cleanups</div><div className="list">{cleanups.map((item) => <div className="list-row" key={item.sender}><div className="avatar"><Mail size={14} /></div><div><strong>{item.sender}</strong><small>{item.count} messages</small></div><div className="muted">{item.reason}</div><div><button className="btn" onClick={() => setApproved((values) => values.includes(item.sender) ? values.filter((value) => value !== item.sender) : [...values, item.sender])}>{approved.includes(item.sender) ? "Selected" : item.action}</button></div></div>)}</div>{approved.length > 0 && <div style={{marginTop:14,display:"flex",justifyContent:"flex-end",gap:8}}><button className="btn" onClick={() => setApproved([])}>Cancel</button><button className="btn primary">Review {approved.length} action{approved.length > 1 ? "s" : ""}</button></div>}</div> }
function Intelligence() { return <div className="page"><PageHeader eyebrow="Preference brain" title="Intelligence" subtitle="Transparent signals shaping what deserves your attention." /><div className="cards"><div className="card"><div className="intel-label">Communication</div><h3>Concise by default</h3><p>Drafts average 3–5 sentences. Business communication is direct and warm.</p><span className="pill">12 learned preferences</span></div><div className="card"><div className="intel-label">Business</div><h3>Strategic partnerships</h3><p>Founder relationships and concrete product opportunities receive higher weight.</p><span className="pill">8 priority signals</span></div><div className="card"><div className="intel-label">Inbox</div><h3>Protect trusted senders</h3><p>Financial, legal, travel, and security messages are never suggested for automatic deletion.</p><span className="pill">7 safety rules</span></div></div></div> }
function Connections({ microsoftConnection }: { microsoftConnection: MicrosoftConnection }) { const router = useRouter(); const [syncing, setSyncing] = useState(false); const [syncError, setSyncError] = useState(""); const [syncResult, setSyncResult] = useState(""); const account = microsoftConnection?.account_name ?? microsoftConnection?.account_identifier; const sync = async () => { setSyncing(true); setSyncError(""); setSyncResult(""); try { const response = await fetch("/api/connectors/microsoft/sync", { method: "POST" }); const result = await response.json() as { imported?: number; error?: string }; if (!response.ok) throw new Error(result.error ?? "The import failed."); setSyncResult(`${result.imported ?? 0} Outlook messages imported. Open Inbox to review them.`); router.refresh(); } catch (error) { setSyncError(error instanceof Error ? error.message : "The import failed."); } finally { setSyncing(false); } }; return <div className="page"><PageHeader eyebrow="Sources" title="Connections" subtitle="Provider integrations are capability-aware and require your approval." />{syncResult && <div className="empty-card">{syncResult}</div>}<div className="list"><div className="list-row"><div className="avatar"><Link2 size={14} /></div><div><strong>Outlook & Microsoft 365</strong><small>{account ?? "Personal, work, and school accounts"}</small></div><div className="muted">{microsoftConnection ? "Connected securely with Microsoft" : "Connect securely with Microsoft"}{syncError && <small className="negative">{syncError}</small>}</div><div>{microsoftConnection ? <div style={{display:"flex",gap:8,alignItems:"center"}}><span className="pill"><CheckCircle2 size={11} /> Connected</span><button className="btn" onClick={sync} disabled={syncing}>{syncing ? "Importing…" : "Import messages"}</button></div> : <a className="btn" href="/api/connectors/microsoft/start">Connect Outlook</a>}</div></div>{["Gmail", "Manual capture", "Instagram", "WhatsApp"].map((name, index) => <div className="list-row" key={name}><div className="avatar"><Link2 size={14} /></div><div><strong>{name}</strong><small>{index === 1 ? "Available" : "Feature flagged"}</small></div><div className="muted">{index === 1 ? "Paste and verify conversations" : "No account connected"}</div><div><button className="btn" disabled={index !== 1}>{index === 1 ? "Open" : "Coming later"}</button></div></div>)}</div></div> }
function SettingsView() { return <div className="page"><PageHeader eyebrow="Private workspace" title="Settings" subtitle="Security and human approval remain the default." /><div className="cards"><div className="card"><CircleUserRound size={17} /><h3>Account & security</h3><p>Supabase Auth architecture with manual provisioning and mandatory TOTP MFA.</p><span className="pill">MFA required</span></div><div className="card"><Sparkles size={17} /><h3>AI & privacy</h3><p>Only relevant context is sent through the AI service boundary. Full inbox access is prohibited.</p><span className="pill">Minimal context</span></div><div className="card"><CheckCircle2 size={17} /><h3>Approval policy</h3><p>Sending, deleting, and unsubscribing always requires explicit confirmation in V1.</p><span className="pill">Human in control</span></div></div></div> }
function CommandBar({ close, go }: { close: () => void; go: (view: View) => void }) { const [query, setQuery] = useState(""); const items = useMemo(() => [{text:"Who do I need to answer today?",view:"today" as View},{text:"Show my smart inbox",view:"inbox" as View},{text:"Show people I promised to contact",view:"followups" as View},{text:"Review low-value newsletters",view:"cleanup" as View}].filter((item) => item.text.toLowerCase().includes(query.toLowerCase())),[query]); return <div className="command-overlay" onMouseDown={close}><div className="command" onMouseDown={(event) => event.stopPropagation()}><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Ask about your communication…" /><div className="command-list">{items.map((item) => <div className="command-item" key={item.text} onClick={() => go(item.view)}><Command size={12} style={{display:"inline",marginRight:8}} />{item.text}</div>)}</div></div></div> }
